CREATE TABLE address (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    street VARCHAR(255) NOT NULL,
    number INTEGER NOT NULL,
    city VARCHAR(255) NOT NULL,
    zipCode VARCHAR(255) NOT NULL
);